
# **MANIPULANDO MATRIZES**

In [1]:
import numpy as np 

In [3]:
matriz1 = np.array([[1,-2,3],
                    [-4,5,6],
                    [7,8,-9]])

array([[ 1, -2,  3],
       [-4,  5,  6],
       [ 7,  8, -9]])

In [5]:
matriz1[0,0]

1

In [6]:
matriz1[0,1]

-2

In [8]:
matriz1[:]

array([[ 1, -2,  3],
       [-4,  5,  6],
       [ 7,  8, -9]])

In [11]:
matriz1[2,:]

array([ 7,  8, -9])

In [12]:
matriz1[:,1]

array([-2,  5,  8])

In [14]:
matriz2 = matriz1.copy()
matriz2

array([[ 1, -2,  3],
       [-4,  5,  6],
       [ 7,  8, -9]])

In [18]:
matriz2[1,0] = 10
matriz2

array([[ 1, -2,  3],
       [10,  5,  6],
       [ 7,  8, -9]])

In [19]:
matriz3 = matriz2[1,:]
matriz3

array([10,  5,  6])

In [21]:
matriz4 = matriz2[:,0]
matriz4

array([ 1, 10,  7])

In [22]:
matriz5 = matriz2[1,1:3]
matriz5

array([5, 6])