# ***CRIAÇÃO DE MATRIZES***

In [ ]:
import numpy as np

In [ ]:
m = [[1,-2,3],
     [-4,5,6],
     [7,8,-9]]

matrix = np.array(m)
matrix

array([[ 1, -2,  3],
       [-4,  5,  6],
       [ 7,  8, -9]])

# ***MATRIZ COM SOMENTE UM NUMERO***


In [ ]:
matrix2 = np.ones([2,3])
matrix2

array([[1., 1., 1.],
       [1., 1., 1.]])

# ***MATRIZ NULA***

In [ ]:
matrix3 = np.zeros([5,2])
matrix3

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

# ***MATRIZ DIAGONAL***

In [ ]:
Matrix4 = np.diag([2,4,6,8])
Matrix4

array([[2, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 6, 0],
       [0, 0, 0, 8]])

# ***MATRIZ IDENTIDADE***

In [ ]:
matrix5 = np.eye(3)
matrix5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# ***MATRIZ TRANSPOSTA***

In [ ]:


matrix6 = np.array(matrix).T
matrix6

array([[ 1, -4,  7],
       [-2,  5,  8],
       [ 3,  6, -9]])

# ***MATRIZ OPOSTA***

In [ ]:
matrix7 = -1*matrix
matrix7

array([[-1,  2, -3],
       [ 4, -5, -6],
       [-7, -8,  9]])

# ***MATRIZ LINHA E MATRIZ COLUNA***

In [ ]:
linha = np.array([[2,3,4,5]])
linha

array([[2, 3, 4, 5]])

In [ ]:
coluna = np.array([[1],[2],[3]])
coluna

array([[1],
       [2],
       [3]])