# **ESTIMATIVA POR MINIMO QUADRADO**

In [1]:
import numpy as np
import scipy as sp
import pandas as pd

# **ANALISE INICIAL**

In [3]:
#Importação do dataframe

nota = pd.read_excel('/content/drive/MyDrive/concurso.xlsx')

In [7]:
nota.head(25)

inicio_estudo  tempo_estudo_dia  nota
0               5               120   8.1
1              13                90   6.8
2              20               120   7.0
3              28                60   7.4
4              20               150   9.3
5              24               150   7.5
6              18                60   7.6
7               8               120   8.0
8               2               240   7.0
9              12                90   7.3
10             15                90   8.6
11              9               120   8.3
12              6               180   7.9
13              4                90   6.4
14              8               150   7.8
15             12               120   9.4
16             10               180   8.8
17              3                90   6.9
18             15               180   7.7
19              9                90   8.2
20             24               120   8.6
21              5               150   8.1
22              7               120   7.2
23             12               180   8.5
24              2                90   6.1

In [6]:
nota.shape

(25, 3)

In [9]:
nota.dtypes

inicio_estudo         int64
tempo_estudo_dia      int64
nota                float64
dtype: object

Valores Missing (NaN)

In [11]:
nota.isnull().sum()

inicio_estudo       0
tempo_estudo_dia    0
nota                0
dtype: int64

# **MATRIZ DOS COEFICIENTES**


In [13]:
nota.head(25)

inicio_estudo  tempo_estudo_dia  nota
0               5               120   8.1
1              13                90   6.8
2              20               120   7.0
3              28                60   7.4
4              20               150   9.3
5              24               150   7.5
6              18                60   7.6
7               8               120   8.0
8               2               240   7.0
9              12                90   7.3
10             15                90   8.6
11              9               120   8.3
12              6               180   7.9
13              4                90   6.4
14              8               150   7.8
15             12               120   9.4
16             10               180   8.8
17              3                90   6.9
18             15               180   7.7
19              9                90   8.2
20             24               120   8.6
21              5               150   8.1
22              7               120   7.2
23             12               180   8.5
24              2                90   6.1

In [14]:
a = nota.drop(columns=['nota'])
a.head()

inicio_estudo  tempo_estudo_dia
0              5               120
1             13                90
2             20               120
3             28                60
4             20               150

In [15]:
type(a)



pandas.core.frame.DataFrame

In [16]:
a = a.values
print(a)

[[  5 120]
 [ 13  90]
 [ 20 120]
 [ 28  60]
 [ 20 150]
 [ 24 150]
 [ 18  60]
 [  8 120]
 [  2 240]
 [ 12  90]
 [ 15  90]
 [  9 120]
 [  6 180]
 [  4  90]
 [  8 150]
 [ 12 120]
 [ 10 180]
 [  3  90]
 [ 15 180]
 [  9  90]
 [ 24 120]
 [  5 150]
 [  7 120]
 [ 12 180]
 [  2  90]]


In [17]:
type(a)

numpy.ndarray

# **MATRIZ DAS CONSTANTES**

In [19]:
b = nota.drop(columns = ['inicio_estudo','tempo_estudo_dia'])
b

nota
0    8.1
1    6.8
2    7.0
3    7.4
4    9.3
5    7.5
6    7.6
7    8.0
8    7.0
9    7.3
10   8.6
11   8.3
12   7.9
13   6.4
14   7.8
15   9.4
16   8.8
17   6.9
18   7.7
19   8.2
20   8.6
21   8.1
22   7.2
23   8.5
24   6.1

In [20]:
b = b.values
b

array([[8.1],
       [6.8],
       [7. ],
       [7.4],
       [9.3],
       [7.5],
       [7.6],
       [8. ],
       [7. ],
       [7.3],
       [8.6],
       [8.3],
       [7.9],
       [6.4],
       [7.8],
       [9.4],
       [8.8],
       [6.9],
       [7.7],
       [8.2],
       [8.6],
       [8.1],
       [7.2],
       [8.5],
       [6.1]])

# **ESTIMATIVA POR MINIMOS QUADRADOS**

In [21]:
# descobrindo a transposta da matriz a
at = np.array(a).T
at

array([[  5,  13,  20,  28,  20,  24,  18,   8,   2,  12,  15,   9,   6,
          4,   8,  12,  10,   3,  15,   9,  24,   5,   7,  12,   2],
       [120,  90, 120,  60, 150, 150,  60, 120, 240,  90,  90, 120, 180,
         90, 150, 120, 180,  90, 180,  90, 120, 150, 120, 180,  90]])

In [22]:
a

array([[  5, 120],
       [ 13,  90],
       [ 20, 120],
       [ 28,  60],
       [ 20, 150],
       [ 24, 150],
       [ 18,  60],
       [  8, 120],
       [  2, 240],
       [ 12,  90],
       [ 15,  90],
       [  9, 120],
       [  6, 180],
       [  4,  90],
       [  8, 150],
       [ 12, 120],
       [ 10, 180],
       [  3,  90],
       [ 15, 180],
       [  9,  90],
       [ 24, 120],
       [  5, 150],
       [  7, 120],
       [ 12, 180],
       [  2,  90]])

In [23]:
# Multiplicação de transposta pela matriz a
ata = np.dot(at,a)
ata

array([[  4669,  34950],
       [ 34950, 441900]])

In [24]:
# calcular a inversa da matriz anterior
inv = np.linalg.inv(ata)
inv

array([[ 5.24991072e-04, -4.15216971e-05],
       [-4.15216971e-05,  5.54691857e-06]])

In [26]:
atb = np.dot(at,b)
atb

array([[ 2305.9],
       [24726. ]])

In [30]:
x = np.dot(inv,atb)
x

array([[0.18391143],
       [0.04140823]])

In [31]:
#clean code
x = np.dot(np.dot(np.linalg.inv(np.dot(at,a)),at),b)
x

array([[0.18391143],
       [0.04140823]])

**nota = 0.1839.inicio_estudo + 0.0414.tempo_estudo_dia**

In [32]:
resultado = nota
resultado

inicio_estudo  tempo_estudo_dia  nota
0               5               120   8.1
1              13                90   6.8
2              20               120   7.0
3              28                60   7.4
4              20               150   9.3
5              24               150   7.5
6              18                60   7.6
7               8               120   8.0
8               2               240   7.0
9              12                90   7.3
10             15                90   8.6
11              9               120   8.3
12              6               180   7.9
13              4                90   6.4
14              8               150   7.8
15             12               120   9.4
16             10               180   8.8
17              3                90   6.9
18             15               180   7.7
19              9                90   8.2
20             24               120   8.6
21              5               150   8.1
22              7               120   7.2
23             12               180   8.5
24              2                90   6.1

In [33]:
resultado['previsao'] = resultado['inicio_estudo']*x[0]+resultado['tempo_estudo_dia']*x[1]
resultado

inicio_estudo  tempo_estudo_dia  nota   previsao
0               5               120   8.1   5.888544
1              13                90   6.8   6.117589
2              20               120   7.0   8.647216
3              28                60   7.4   7.634014
4              20               150   9.3   9.889463
5              24               150   7.5  10.625108
6              18                60   7.6   5.794899
7               8               120   8.0   6.440279
8               2               240   7.0  10.305797
9              12                90   7.3   5.933678
10             15                90   8.6   6.485412
11              9               120   8.3   6.624190
12              6               180   7.9   8.556949
13              4                90   6.4   4.462386
14              8               150   7.8   7.682525
15             12               120   9.4   7.175924
16             10               180   8.8   9.292595
17              3                90   6.9   4.278475
18             15               180   7.7  10.212152
19              9                90   8.2   5.381943
20             24               120   8.6   9.382862
21              5               150   8.1   7.130791
22              7               120   7.2   6.256367
23             12               180   8.5   9.660418
24              2                90   6.1   4.094563

In [34]:
# Erro medio absoluto (MAE)
from sklearn.metrics import mean_absolute_error
mean_absolute_error(resultado.nota, resultado.previsao)

1.5823602999826787

In [35]:
resultado['erro_abs'] = abs (resultado.nota - resultado.previsao)
resultado

inicio_estudo  tempo_estudo_dia  nota   previsao  erro_abs
0               5               120   8.1   5.888544  2.211456
1              13                90   6.8   6.117589  0.682411
2              20               120   7.0   8.647216  1.647216
3              28                60   7.4   7.634014  0.234014
4              20               150   9.3   9.889463  0.589463
5              24               150   7.5  10.625108  3.125108
6              18                60   7.6   5.794899  1.805101
7               8               120   8.0   6.440279  1.559721
8               2               240   7.0  10.305797  3.305797
9              12                90   7.3   5.933678  1.366322
10             15                90   8.6   6.485412  2.114588
11              9               120   8.3   6.624190  1.675810
12              6               180   7.9   8.556949  0.656949
13              4                90   6.4   4.462386  1.937614
14              8               150   7.8   7.682525  0.117475
15             12               120   9.4   7.175924  2.224076
16             10               180   8.8   9.292595  0.492595
17              3                90   6.9   4.278475  2.621525
18             15               180   7.7  10.212152  2.512152
19              9                90   8.2   5.381943  2.818057
20             24               120   8.6   9.382862  0.782862
21              5               150   8.1   7.130791  0.969209
22              7               120   7.2   6.256367  0.943633
23             12               180   8.5   9.660418  1.160418
24              2                90   6.1   4.094563  2.005437