In [1]:
import scipy as sp
from scipy import linalg 
import numpy as np

In [23]:
matriz = np.array([[1,2,3],
                   [2,-1,1],
                   [-2,-3,3]])

vetor = np.array([2,-1,-11])


In [24]:
np.array([matriz[:,0],matriz[:,1],matriz[:,2]])

array([[ 1,  2, -2],
       [ 2, -1, -3],
       [ 3,  1,  3]])

In [25]:
np.array([matriz[:,0],matriz[:,1],matriz[:,2]]).T

array([[ 1,  2,  3],
       [ 2, -1,  1],
       [-2, -3,  3]])

In [19]:
def cramer (a,b):
  det = sp.linalg.det(np.array([a[:,0],a[:,1],a[:,2]]).T)
  if det != 0:
    detx = sp.linalg.det(np.array([b[:],a[:,1],a[:,2]]).T)
    dety = sp.linalg.det(np.array([a[:,0],b[:],a[:,2]]).T)
    detz = sp.linalg.det(np.array([a[:,0],a[:,1],b[:]]).T)

    x = detx/det
    y = dety/det
    z = detz/det

    print(f'O valor de X é {x:.2f}')
    print(f'O valor de Y é {y:.2f}')
    print(f'O valor de Z é {z:.2f}')
    
  else:
      print('A determinante dos coeficientes é nula')

In [26]:
cramer(matriz,vetor)

O valor de x é 1.00
O valor de y é 2.00
O valor de z é -1.00


In [27]:
matriz2 = np.array([[3,2,7],
                    [4,-29,3],
                    [2,3,5]])

matriz2

array([[  3,   2,   7],
       [  4, -29,   3],
       [  2,   3,   5]])

In [28]:
vetor2 = np.array([1,2,2])
vetor2

array([1, 2, 2])

In [29]:
cramer(matriz2,vetor2)

A determinante dos coeficientes é nula


In [30]:
sp.linalg.det(matriz2)

0.0

In [33]:
def cramer2 (A,b):
  det = sp.linalg.det(np.array([A[:,0],A[:,1]]).T)
  if det != 0:
    detx = sp.linalg.det(np.array([b[:],A[:,1]]).T)
    dety = sp.linalg.det(np.array([A[:,0],b[:]]).T)

    x = detx/det
    y = dety/det
    
    print('O valor de x é {:.2f}'.format (x))
    print('O valor de y é {:.2f}'.format (y))
  else:
    print("Determinante da matriz dos coeficientes é nula")

In [34]:
matriz3 = np.array([[1,4],
                   [2,3]])


vetor3 = np.array([200,180])

In [35]:
cramer2(matriz3,vetor3)

O valor de x é 24.00
O valor de y é 44.00
