In [2]:
import numpy as np


In [3]:
a = np.array([[3,0],
              [0,1]])
a

array([[3, 0],
       [0, 1]])

In [4]:
autovalor, autovetor = np.linalg.eig(a)

In [5]:
autovalor

array([3., 1.])

In [6]:
autovetor

array([[1., 0.],
       [0., 1.]])

In [11]:
print('O autovalor {:.3f} está associado aos autovetores {:.3f} e {:.3f}'.format(autovalor[0],autovetor[0][0],autovetor[1][0]))
print('O autovalor {:.3f} está associado aos autovetores {:.3f} e {:.3f}'.format(autovalor[1],autovetor[0][1],autovetor[1][1]))

O autovalor 2.000 está associado aos autovetores 0.832 e 0.555
O autovalor 1.000 está associado aos autovetores 0.707 e 0.707


In [12]:
b = np.array([[4,-3],
              [2,-1]])

In [13]:
autovalor, autovetor = np.linalg.eig(b)
print('O autovalor {:.3f} está associado aos autovetores {:.3f} e {:.3f}'.format(autovalor[0],autovetor[0][0],autovetor[1][0]))
print('O autovalor {:.3f} está associado aos autovetores {:.3f} e {:.3f}'.format(autovalor[1],autovetor[0][1],autovetor[1][1]))

O autovalor 2.000 está associado aos autovetores 0.832 e 0.555
O autovalor 1.000 está associado aos autovetores 0.707 e 0.707
