In [21]:
import numpy as np
import pandas as pd

# **ANALISE INICIAL**

In [6]:
# importação do datafram
massa = pd.read_csv('/content/drive/MyDrive/inspecao.csv', sep=';')

In [7]:
massa.head()

amostra     A     B
0        1   9.9   9.7
1        2  10.2  10.5
2        3  10.0  10.7
3        4  10.4   9.8
4        5   9.7  10.0

In [8]:
massa.shape

(22, 3)

Valores Missing (NaN)

In [14]:
#indicação da quantidade de valores faltantes
massa.isnull().sum()

amostra    0
A          0
B          0
dtype: int64

In [15]:
#exclusao do valores faltantes
massa = massa.dropna()
massa

amostra     A     B
0         1   9.9   9.7
1         2  10.2  10.5
2         3  10.0  10.7
3         4  10.4   9.8
4         5   9.7  10.0
5         6   9.7  10.1
6         7  11.7  11.5
7         8  11.0  10.8
8         9   8.7   8.8
9        10   9.5   9.3
10       11  10.1   9.4
11       12   9.6   9.6
12       13  10.5  10.4
13       14   9.2   9.0
14       15  11.3  11.6
15       16  10.1   9.8
16       17   8.5   9.2
18       19   9.6  10.0
19       20  10.3   9.5
20       21  10.5   9.8
21       22   9.3   9.9

In [16]:
massa.shape

(21, 3)

# **CRIAÇÃO DA MATRIZ DE COVARIÂNCIA**

In [18]:
matriz = massa.drop(columns=['amostra'])
matriz

A     B
0    9.9   9.7
1   10.2  10.5
2   10.0  10.7
3   10.4   9.8
4    9.7  10.0
5    9.7  10.1
6   11.7  11.5
7   11.0  10.8
8    8.7   8.8
9    9.5   9.3
10  10.1   9.4
11   9.6   9.6
12  10.5  10.4
13   9.2   9.0
14  11.3  11.6
15  10.1   9.8
16   8.5   9.2
18   9.6  10.0
19  10.3   9.5
20  10.5   9.8
21   9.3   9.9

In [19]:
matriz = matriz.values
print(matriz)

[[ 9.9  9.7]
 [10.2 10.5]
 [10.  10.7]
 [10.4  9.8]
 [ 9.7 10. ]
 [ 9.7 10.1]
 [11.7 11.5]
 [11.  10.8]
 [ 8.7  8.8]
 [ 9.5  9.3]
 [10.1  9.4]
 [ 9.6  9.6]
 [10.5 10.4]
 [ 9.2  9. ]
 [11.3 11.6]
 [10.1  9.8]
 [ 8.5  9.2]
 [ 9.6 10. ]
 [10.3  9.5]
 [10.5  9.8]
 [ 9.3  9.9]]


In [23]:
matriz_cov = np.cov(np.transpose(matriz))
matriz_cov

# o 0.61 é a variancia do produto a
# o 0.54 é a variancia do produto b
# o 0.47 é a covariancia entre a e b

array([[0.61090476, 0.47271429],
       [0.47271429, 0.54514286]])

# **AUTOVALORES E AUTOVETORES DA MATRIZ DE COVARIANCIA**

In [24]:
autovalor, autovetor = np.linalg.eig(matriz_cov)
print('O autovalor {:.3f} está associado aos autovetores {:.3f} e {:.3f}'.format(autovalor[0],autovetor[0][0],autovetor[1][0]))
print('O autovalor {:.3f} está associado aos autovetores {:.3f} e {:.3f}'.format(autovalor[1],autovetor[0][1],autovetor[1][1]))

O autovalor 1.052 está associado aos autovetores 0.731 e 0.682
O autovalor 0.104 está associado aos autovetores -0.682 e 0.731


# **TAXA DE VARIÂNCIA EXPLICADA (EVR)**

In [25]:
evr = autovalor/np.sum(autovalor)
evr

array([0.90989356, 0.09010644])

Os componentes principais neste caso serão os autovetores 0,731 e 0,682