# **CRIAÇÃO DE MATRIZ**

In [1]:
import numpy as np

In [2]:
matriz1 = np.array([[2,5],
                    [1,3]])

matriz2 = np.array([[3, -5],
                    [-1,2]])

In [3]:
multi = np.dot(matriz1, matriz2)
multi

array([[1, 0],
       [0, 1]])

# **MATRIZ INVERSA**

In [4]:
matriz_inv = np.linalg.inv(matriz1)
matriz_inv

array([[ 3., -5.],
       [-1.,  2.]])

In [5]:
matriz_inv2 = np.linalg.inv(matriz2)
matriz_inv2

array([[2., 5.],
       [1., 3.]])

In [7]:
matriz3 = np.array([[-11,2,2],
                    [-4,0,1],
                    [6,-1,-1]])

In [8]:
matriz_inv3 = np.linalg.inv(matriz3)
matriz_inv3

array([[ 1.00000000e+00, -2.42230478e-16,  2.00000000e+00],
       [ 2.00000000e+00, -1.00000000e+00,  3.00000000e+00],
       [ 4.00000000e+00,  1.00000000e+00,  8.00000000e+00]])

In [9]:
matriz4 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

In [ ]:
matriz_inv4 = np.linalg.inv(matriz4)
matriz_inv4

# **DETERMINANTE**

In [13]:
matriz5 = np.array([[1,3,2],
                    [4,2,4],
                    [3,1,5]])

In [15]:
det5 = np.linalg.det(matriz5)
det5

-22.000000000000004

In [16]:
import scipy as sp
from scipy import linalg

In [17]:
det5 = sp.linalg.det(matriz5)
det5

-22.0

In [19]:
matriz6 = np.array([[2,4],
                    [3,8]])

det6 = np.linalg.det(matriz6)
det6

3.999999999999999

In [20]:
det6 = sp.linalg.det(matriz6)
det6

4.0

In [21]:
matriz7 = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

det7 = np.linalg.det(matriz7)
det7

0.0

In [22]:
det7 = sp.linalg.det(matriz7)
det7

0.0

In [23]:
matriz8 = np.array([[1,3,0,-2,1],
                    [4,2,4,5,4],
                    [0,1,5,-3,2],
                    [-2,3,1,0,7],
                    [0,1,9,3,2]])

det8 = sp.linalg.det(matriz8)
det8

3592.000000000001