# **OPERAÇÕES COM MATRIZES**

In [11]:
import numpy as np 

In [12]:
matrizA = np.array([[2,-3],
                    [4,-6],
                    [6, 9]])

In [13]:
matrizB = np.array([[1,7],
                    [-3,4],
                    [5,-8]])

# **SOMA DE MATRIZES**

In [9]:
somaAB = matrizA + matrizB
somaAB

array([[ 3,  4],
       [ 1, -2],
       [11,  1]])

# **SUBTRAÇÃO DE MATRIZES**

In [10]:
subAB = matrizA - matrizB
subAB

array([[  1, -10],
       [  7, -10],
       [  1,  17]])

# **MULTIPLICAÇÃO POR UM ESCALAR**


In [15]:
Multi1 = 2*matrizA
Multi1

array([[  4,  -6],
       [  8, -12],
       [ 12,  18]])

In [16]:
Multi2 = 3*matrizB
Multi2

array([[  3,  21],
       [ -9,  12],
       [ 15, -24]])

# **MULTIPLICAÇÃO DE MATRIZES**

In [20]:
matrizC = np.array([[2,1],
                    [3,4],
                    [5,6]])

matrizD = np.array([[7,8,0],
                    [10,5,-2]])


In [21]:
multiCD = np.dot(matrizC,matrizD)
multiCD

array([[ 24,  21,  -2],
       [ 61,  44,  -8],
       [ 95,  70, -12]])

In [22]:
multiDC = np.dot(matrizD,matrizC)
multiDC

array([[38, 39],
       [25, 18]])