# **CÁLCULO COM VETORES**


In [4]:
import numpy as np

u = [2,-4,1]



In [5]:
u = np.array(u)

In [6]:
type(u)

numpy.ndarray

In [7]:
u.shape

(3,)

In [8]:
v = np.array([3,2,-5])

#**SOMA DE VETORES**

In [9]:
print(u)

[ 2 -4  1]


In [10]:
print(v)

[ 3  2 -5]


In [11]:
soma = u + v
print(soma)

[ 5 -2 -4]


# **PRODUTO INTERNO**

In [12]:
u * v

array([ 6, -8, -5])

In [13]:
prod_inter = 0
for i in range(len(u)):
  prod_inter = prod_inter + u[i] * v[i]
  i = i + 1

prod_inter

-7

# **MULTIPLICAÇÃO ESCALAR**

In [18]:
print(u)
print(v)

[ 2 -4  1]
[ 3  2 -5]


In [14]:
multi = 5*u
multi

array([ 10, -20,   5])

In [16]:
multi2 = 5*v
multi2

array([ 15,  10, -25])